#!/usr/bin/env bash
exec copilot \
  --no-custom-instructions \
  --disable-builtin-mcps \
  --no-bash-env \
  --no-remote \
  --no-auto-update \
  --no-ask-user \
  --disallow-temp-dir \
  --available-tools \
  --no-color \
  --silent \
  --model "gpt-4.1" \
  --config-dir /tmp \
  "$@"
