#!/usr/bin/env bash
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BROWN='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'

RESET='\033[0m' # No Color
NC=$RESET


function statusmsg {
  local msg="$1"
  echo -e "$BLUE::$RESET ${msg}"
}
